var annotated_dup =
[
    [ "Catch", "namespace_catch.html", [
      [ "Detail", "namespace_catch_1_1_detail.html", [
        [ "Approx", "class_catch_1_1_detail_1_1_approx.html", "class_catch_1_1_detail_1_1_approx" ],
        [ "EnumInfo", "struct_catch_1_1_detail_1_1_enum_info.html", "struct_catch_1_1_detail_1_1_enum_info" ],
        [ "IsStreamInsertable", "class_catch_1_1_detail_1_1_is_stream_insertable.html", null ]
      ] ],
      [ "detail", "namespace_catch_1_1detail.html", [
        [ "is_range_impl", "struct_catch_1_1detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >", "struct_catch_1_1detail_1_1is__range__impl_3_01_t_00_01typename_01void__type_3_01decltype_07begin8604ecb9de16ea7789f2f694ac896ffd.html", null ],
        [ "void_type", "struct_catch_1_1detail_1_1void__type.html", "struct_catch_1_1detail_1_1void__type" ]
      ] ],
      [ "Generators", "namespace_catch_1_1_generators.html", [
        [ "as", "struct_catch_1_1_generators_1_1as.html", null ],
        [ "ChunkGenerator", "class_catch_1_1_generators_1_1_chunk_generator.html", "class_catch_1_1_generators_1_1_chunk_generator" ],
        [ "FilterGenerator", "class_catch_1_1_generators_1_1_filter_generator.html", "class_catch_1_1_generators_1_1_filter_generator" ],
        [ "FixedValuesGenerator", "class_catch_1_1_generators_1_1_fixed_values_generator.html", "class_catch_1_1_generators_1_1_fixed_values_generator" ],
        [ "Generators", "class_catch_1_1_generators_1_1_generators.html", "class_catch_1_1_generators_1_1_generators" ],
        [ "GeneratorUntypedBase", "class_catch_1_1_generators_1_1_generator_untyped_base.html", "class_catch_1_1_generators_1_1_generator_untyped_base" ],
        [ "GeneratorWrapper", "class_catch_1_1_generators_1_1_generator_wrapper.html", "class_catch_1_1_generators_1_1_generator_wrapper" ],
        [ "IGenerator", "struct_catch_1_1_generators_1_1_i_generator.html", "struct_catch_1_1_generators_1_1_i_generator" ],
        [ "IteratorGenerator", "class_catch_1_1_generators_1_1_iterator_generator.html", "class_catch_1_1_generators_1_1_iterator_generator" ],
        [ "MapGenerator", "class_catch_1_1_generators_1_1_map_generator.html", "class_catch_1_1_generators_1_1_map_generator" ],
        [ "RandomFloatingGenerator", "class_catch_1_1_generators_1_1_random_floating_generator.html", "class_catch_1_1_generators_1_1_random_floating_generator" ],
        [ "RandomIntegerGenerator", "class_catch_1_1_generators_1_1_random_integer_generator.html", "class_catch_1_1_generators_1_1_random_integer_generator" ],
        [ "RangeGenerator", "class_catch_1_1_generators_1_1_range_generator.html", "class_catch_1_1_generators_1_1_range_generator" ],
        [ "RepeatGenerator", "class_catch_1_1_generators_1_1_repeat_generator.html", "class_catch_1_1_generators_1_1_repeat_generator" ],
        [ "SingleValueGenerator", "class_catch_1_1_generators_1_1_single_value_generator.html", "class_catch_1_1_generators_1_1_single_value_generator" ],
        [ "TakeGenerator", "class_catch_1_1_generators_1_1_take_generator.html", "class_catch_1_1_generators_1_1_take_generator" ]
      ] ],
      [ "Matchers", "namespace_catch_1_1_matchers.html", [
        [ "Exception", "namespace_catch_1_1_matchers_1_1_exception.html", [
          [ "ExceptionMessageMatcher", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher.html", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher" ]
        ] ],
        [ "Floating", "namespace_catch_1_1_matchers_1_1_floating.html", [
          [ "WithinAbsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher" ],
          [ "WithinRelMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher" ],
          [ "WithinUlpsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher" ]
        ] ],
        [ "Generic", "namespace_catch_1_1_matchers_1_1_generic.html", [
          [ "PredicateMatcher", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher.html", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher" ]
        ] ],
        [ "Impl", "namespace_catch_1_1_matchers_1_1_impl.html", [
          [ "MatchAllOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of" ],
          [ "MatchAnyOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of" ],
          [ "MatcherBase", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base" ],
          [ "MatcherMethod", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method" ],
          [ "MatcherUntypedBase", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base.html", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base" ],
          [ "MatchNotOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of" ]
        ] ],
        [ "StdString", "namespace_catch_1_1_matchers_1_1_std_string.html", [
          [ "CasedString", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher" ],
          [ "EndsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher" ],
          [ "RegexMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher" ],
          [ "StartsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher" ],
          [ "StringMatcherBase", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base" ]
        ] ],
        [ "Vector", "namespace_catch_1_1_matchers_1_1_vector.html", [
          [ "ApproxMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher" ],
          [ "ContainsElementMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher" ],
          [ "UnorderedEqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher" ]
        ] ]
      ] ],
      [ "always_false", "struct_catch_1_1always__false.html", null ],
      [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", "class_catch_1_1_assertion_handler" ],
      [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", "struct_catch_1_1_assertion_info" ],
      [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", "struct_catch_1_1_assertion_reaction" ],
      [ "AutoReg", "struct_catch_1_1_auto_reg.html", "struct_catch_1_1_auto_reg" ],
      [ "BinaryExpr", "class_catch_1_1_binary_expr.html", "class_catch_1_1_binary_expr" ],
      [ "Capturer", "class_catch_1_1_capturer.html", "class_catch_1_1_capturer" ],
      [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", "struct_catch_1_1_case_sensitive" ],
      [ "Counts", "struct_catch_1_1_counts.html", "struct_catch_1_1_counts" ],
      [ "Decomposer", "struct_catch_1_1_decomposer.html", "struct_catch_1_1_decomposer" ],
      [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", "class_catch_1_1_exception_translator_registrar" ],
      [ "ExprLhs", "class_catch_1_1_expr_lhs.html", "class_catch_1_1_expr_lhs" ],
      [ "GeneratorException", "class_catch_1_1_generator_exception.html", "class_catch_1_1_generator_exception" ],
      [ "IConfig", "struct_catch_1_1_i_config.html", "struct_catch_1_1_i_config" ],
      [ "IContext", "struct_catch_1_1_i_context.html", "struct_catch_1_1_i_context" ],
      [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", "struct_catch_1_1_i_exception_translator" ],
      [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", "struct_catch_1_1_i_exception_translator_registry" ],
      [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", "struct_catch_1_1_i_generator_tracker" ],
      [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", "struct_catch_1_1_i_mutable_context" ],
      [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", "struct_catch_1_1_i_mutable_enum_values_registry" ],
      [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", "struct_catch_1_1_i_mutable_registry_hub" ],
      [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", "struct_catch_1_1_i_registry_hub" ],
      [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", "struct_catch_1_1_i_result_capture" ],
      [ "IRunner", "struct_catch_1_1_i_runner.html", "struct_catch_1_1_i_runner" ],
      [ "is_callable", "struct_catch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "struct_catch_1_1is__callable_3_01_fun_07_args_8_8_8_08_4.html", null ],
      [ "is_callable_tester", "struct_catch_1_1is__callable__tester.html", null ],
      [ "is_range", "struct_catch_1_1is__range.html", null ],
      [ "IStream", "struct_catch_1_1_i_stream.html", "struct_catch_1_1_i_stream" ],
      [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", "struct_catch_1_1_i_test_case_registry" ],
      [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", "struct_catch_1_1_i_test_invoker" ],
      [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", "struct_catch_1_1_i_transient_expression" ],
      [ "LazyExpression", "class_catch_1_1_lazy_expression.html", "class_catch_1_1_lazy_expression" ],
      [ "MatchExpr", "class_catch_1_1_match_expr.html", "class_catch_1_1_match_expr" ],
      [ "MessageBuilder", "struct_catch_1_1_message_builder.html", "struct_catch_1_1_message_builder" ],
      [ "MessageInfo", "struct_catch_1_1_message_info.html", "struct_catch_1_1_message_info" ],
      [ "MessageStream", "struct_catch_1_1_message_stream.html", "struct_catch_1_1_message_stream" ],
      [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", "struct_catch_1_1_name_and_tags" ],
      [ "NonCopyable", "class_catch_1_1_non_copyable.html", "class_catch_1_1_non_copyable" ],
      [ "Option", "class_catch_1_1_option.html", "class_catch_1_1_option" ],
      [ "pluralise", "struct_catch_1_1pluralise.html", "struct_catch_1_1pluralise" ],
      [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", "struct_catch_1_1_registrar_for_tag_aliases" ],
      [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", "struct_catch_1_1_result_disposition" ],
      [ "ResultWas", "struct_catch_1_1_result_was.html", "struct_catch_1_1_result_was" ],
      [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", "class_catch_1_1_reusable_string_stream" ],
      [ "RunTests", "struct_catch_1_1_run_tests.html", "struct_catch_1_1_run_tests" ],
      [ "ScopedMessage", "class_catch_1_1_scoped_message.html", "class_catch_1_1_scoped_message" ],
      [ "Section", "class_catch_1_1_section.html", "class_catch_1_1_section" ],
      [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", "struct_catch_1_1_section_end_info" ],
      [ "SectionInfo", "struct_catch_1_1_section_info.html", "struct_catch_1_1_section_info" ],
      [ "ShowDurations", "struct_catch_1_1_show_durations.html", "struct_catch_1_1_show_durations" ],
      [ "SimplePcg32", "class_catch_1_1_simple_pcg32.html", "class_catch_1_1_simple_pcg32" ],
      [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", "struct_catch_1_1_source_line_info" ],
      [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", "struct_catch_1_1_stream_end_stop" ],
      [ "StringMaker", "struct_catch_1_1_string_maker.html", null ],
      [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", null ],
      [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", null ],
      [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", null ],
      [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", null ],
      [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", null ],
      [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", null ],
      [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", null ],
      [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", null ],
      [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", null ],
      [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", null ],
      [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", null ],
      [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", null ],
      [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", null ],
      [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", null ],
      [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", null ],
      [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
      [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t_0f_s_z_0e_4.html", null ],
      [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", null ],
      [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", null ],
      [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", null ],
      [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", null ],
      [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", null ],
      [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", null ],
      [ "StringRef", "class_catch_1_1_string_ref.html", "class_catch_1_1_string_ref" ],
      [ "TestCase", "class_catch_1_1_test_case.html", "class_catch_1_1_test_case" ],
      [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", "struct_catch_1_1_test_case_info" ],
      [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
      [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", "class_catch_1_1_test_invoker_as_method" ],
      [ "Timer", "class_catch_1_1_timer.html", "class_catch_1_1_timer" ],
      [ "Totals", "struct_catch_1_1_totals.html", "struct_catch_1_1_totals" ],
      [ "true_given", "struct_catch_1_1true__given.html", null ],
      [ "UnaryExpr", "class_catch_1_1_unary_expr.html", "class_catch_1_1_unary_expr" ],
      [ "UseColour", "struct_catch_1_1_use_colour.html", "struct_catch_1_1_use_colour" ],
      [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", "struct_catch_1_1_wait_for_keypress" ],
      [ "WarnAbout", "struct_catch_1_1_warn_about.html", "struct_catch_1_1_warn_about" ]
    ] ],
    [ "Json", "namespace_json.html", [
      [ "BuiltStyledStreamWriter", "struct_json_1_1_built_styled_stream_writer.html", "struct_json_1_1_built_styled_stream_writer" ],
      [ "CharReader", "class_json_1_1_char_reader.html", "class_json_1_1_char_reader" ],
      [ "CharReaderBuilder", "class_json_1_1_char_reader_builder.html", "class_json_1_1_char_reader_builder" ],
      [ "CommentStyle", "struct_json_1_1_comment_style.html", "struct_json_1_1_comment_style" ],
      [ "Exception", "class_json_1_1_exception.html", "class_json_1_1_exception" ],
      [ "FastWriter", "class_json_1_1_fast_writer.html", "class_json_1_1_fast_writer" ],
      [ "Features", "class_json_1_1_features.html", "class_json_1_1_features" ],
      [ "LogicError", "class_json_1_1_logic_error.html", "class_json_1_1_logic_error" ],
      [ "OurCharReader", "class_json_1_1_our_char_reader.html", "class_json_1_1_our_char_reader" ],
      [ "OurFeatures", "class_json_1_1_our_features.html", "class_json_1_1_our_features" ],
      [ "OurReader", "class_json_1_1_our_reader.html", "class_json_1_1_our_reader" ],
      [ "Path", "class_json_1_1_path.html", "class_json_1_1_path" ],
      [ "PathArgument", "class_json_1_1_path_argument.html", "class_json_1_1_path_argument" ],
      [ "Reader", "class_json_1_1_reader.html", "class_json_1_1_reader" ],
      [ "RuntimeError", "class_json_1_1_runtime_error.html", "class_json_1_1_runtime_error" ],
      [ "SecureAllocator", "class_json_1_1_secure_allocator.html", "class_json_1_1_secure_allocator" ],
      [ "StaticString", "class_json_1_1_static_string.html", "class_json_1_1_static_string" ],
      [ "StreamWriter", "class_json_1_1_stream_writer.html", "class_json_1_1_stream_writer" ],
      [ "StreamWriterBuilder", "class_json_1_1_stream_writer_builder.html", "class_json_1_1_stream_writer_builder" ],
      [ "StyledStreamWriter", "class_json_1_1_styled_stream_writer.html", "class_json_1_1_styled_stream_writer" ],
      [ "StyledWriter", "class_json_1_1_styled_writer.html", "class_json_1_1_styled_writer" ],
      [ "Value", "class_json_1_1_value.html", "class_json_1_1_value" ],
      [ "ValueConstIterator", "class_json_1_1_value_const_iterator.html", "class_json_1_1_value_const_iterator" ],
      [ "ValueIterator", "class_json_1_1_value_iterator.html", "class_json_1_1_value_iterator" ],
      [ "ValueIteratorBase", "class_json_1_1_value_iterator_base.html", "class_json_1_1_value_iterator_base" ],
      [ "Writer", "class_json_1_1_writer.html", "class_json_1_1_writer" ]
    ] ],
    [ "Card", "struct_card.html", "struct_card" ],
    [ "Catch_global_namespace_dummy", "struct_catch__global__namespace__dummy.html", null ],
    [ "Deck", "class_deck.html", "class_deck" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameDriver", "class_game_driver.html", "class_game_driver" ],
    [ "Hand", "class_hand.html", "class_hand" ],
    [ "InputOutput", "class_input_output.html", "class_input_output" ],
    [ "JsonPokerTests", "class_json_poker_tests.html", "class_json_poker_tests" ],
    [ "PokerGame", "class_poker_game.html", "class_poker_game" ],
    [ "Statistic", "class_statistic.html", "class_statistic" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ]
];