var annotated_dup =
[
    [ "Catch", "namespace_catch.html", [
      [ "Detail", "namespace_catch_1_1_detail.html", [
        [ "Approx", "class_catch_1_1_detail_1_1_approx.html", "class_catch_1_1_detail_1_1_approx" ],
        [ "EnumInfo", "struct_catch_1_1_detail_1_1_enum_info.html", "struct_catch_1_1_detail_1_1_enum_info" ],
        [ "IsStreamInsertable", "class_catch_1_1_detail_1_1_is_stream_insertable.html", null ]
      ] ],
      [ "detail", "namespace_catch_1_1detail.html", [
        [ "is_range_impl", "struct_catch_1_1detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >", "struct_catch_1_1detail_1_1is__range__impl_3_01_t_00_01typename_01void__type_3_01decltype_07begin8604ecb9de16ea7789f2f694ac896ffd.html", null ],
        [ "void_type", "struct_catch_1_1detail_1_1void__type.html", "struct_catch_1_1detail_1_1void__type" ]
      ] ],
      [ "Generators", "namespace_catch_1_1_generators.html", [
        [ "as", "struct_catch_1_1_generators_1_1as.html", null ],
        [ "ChunkGenerator", "class_catch_1_1_generators_1_1_chunk_generator.html", "class_catch_1_1_generators_1_1_chunk_generator" ],
        [ "FilterGenerator", "class_catch_1_1_generators_1_1_filter_generator.html", "class_catch_1_1_generators_1_1_filter_generator" ],
        [ "FixedValuesGenerator", "class_catch_1_1_generators_1_1_fixed_values_generator.html", "class_catch_1_1_generators_1_1_fixed_values_generator" ],
        [ "Generators", "class_catch_1_1_generators_1_1_generators.html", "class_catch_1_1_generators_1_1_generators" ],
        [ "GeneratorUntypedBase", "class_catch_1_1_generators_1_1_generator_untyped_base.html", "class_catch_1_1_generators_1_1_generator_untyped_base" ],
        [ "GeneratorWrapper", "class_catch_1_1_generators_1_1_generator_wrapper.html", "class_catch_1_1_generators_1_1_generator_wrapper" ],
        [ "IGenerator", "struct_catch_1_1_generators_1_1_i_generator.html", "struct_catch_1_1_generators_1_1_i_generator" ],
        [ "IteratorGenerator", "class_catch_1_1_generators_1_1_iterator_generator.html", "class_catch_1_1_generators_1_1_iterator_generator" ],
        [ "MapGenerator", "class_catch_1_1_generators_1_1_map_generator.html", "class_catch_1_1_generators_1_1_map_generator" ],
        [ "RandomFloatingGenerator", "class_catch_1_1_generators_1_1_random_floating_generator.html", "class_catch_1_1_generators_1_1_random_floating_generator" ],
        [ "RandomIntegerGenerator", "class_catch_1_1_generators_1_1_random_integer_generator.html", "class_catch_1_1_generators_1_1_random_integer_generator" ],
        [ "RangeGenerator", "class_catch_1_1_generators_1_1_range_generator.html", "class_catch_1_1_generators_1_1_range_generator" ],
        [ "RepeatGenerator", "class_catch_1_1_generators_1_1_repeat_generator.html", "class_catch_1_1_generators_1_1_repeat_generator" ],
        [ "SingleValueGenerator", "class_catch_1_1_generators_1_1_single_value_generator.html", "class_catch_1_1_generators_1_1_single_value_generator" ],
        [ "TakeGenerator", "class_catch_1_1_generators_1_1_take_generator.html", "class_catch_1_1_generators_1_1_take_generator" ]
      ] ],
      [ "Matchers", "namespace_catch_1_1_matchers.html", [
        [ "Exception", "namespace_catch_1_1_matchers_1_1_exception.html", [
          [ "ExceptionMessageMatcher", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher.html", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher" ]
        ] ],
        [ "Floating", "namespace_catch_1_1_matchers_1_1_floating.html", [
          [ "WithinAbsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher" ],
          [ "WithinRelMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher" ],
          [ "WithinUlpsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher.html", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher" ]
        ] ],
        [ "Generic", "namespace_catch_1_1_matchers_1_1_generic.html", [
          [ "PredicateMatcher", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher.html", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher" ]
        ] ],
        [ "Impl", "namespace_catch_1_1_matchers_1_1_impl.html", [
          [ "MatchAllOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of" ],
          [ "MatchAnyOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of" ],
          [ "MatcherBase", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base" ],
          [ "MatcherMethod", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method.html", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method" ],
          [ "MatcherUntypedBase", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base.html", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base" ],
          [ "MatchNotOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of.html", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of" ]
        ] ],
        [ "StdString", "namespace_catch_1_1_matchers_1_1_std_string.html", [
          [ "CasedString", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher" ],
          [ "EndsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher" ],
          [ "RegexMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher" ],
          [ "StartsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher" ],
          [ "StringMatcherBase", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base.html", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base" ]
        ] ],
        [ "Vector", "namespace_catch_1_1_matchers_1_1_vector.html", [
          [ "ApproxMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher" ],
          [ "ContainsElementMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher" ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher" ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher" ],
          [ "UnorderedEqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher.html", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher" ]
        ] ]
      ] ],
      [ "always_false", "struct_catch_1_1always__false.html", null ],
      [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", "class_catch_1_1_assertion_handler" ],
      [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", "struct_catch_1_1_assertion_info" ],
      [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", "struct_catch_1_1_assertion_reaction" ],
      [ "AutoReg", "struct_catch_1_1_auto_reg.html", "struct_catch_1_1_auto_reg" ],
      [ "BinaryExpr", "class_catch_1_1_binary_expr.html", "class_catch_1_1_binary_expr" ],
      [ "Capturer", "class_catch_1_1_capturer.html", "class_catch_1_1_capturer" ],
      [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", "struct_catch_1_1_case_sensitive" ],
      [ "Counts", "struct_catch_1_1_counts.html", "struct_catch_1_1_counts" ],
      [ "Decomposer", "struct_catch_1_1_decomposer.html", "struct_catch_1_1_decomposer" ],
      [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", "class_catch_1_1_exception_translator_registrar" ],
      [ "ExprLhs", "class_catch_1_1_expr_lhs.html", "class_catch_1_1_expr_lhs" ],
      [ "GeneratorException", "class_catch_1_1_generator_exception.html", "class_catch_1_1_generator_exception" ],
      [ "IConfig", "struct_catch_1_1_i_config.html", "struct_catch_1_1_i_config" ],
      [ "IContext", "struct_catch_1_1_i_context.html", "struct_catch_1_1_i_context" ],
      [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", "struct_catch_1_1_i_exception_translator" ],
      [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", "struct_catch_1_1_i_exception_translator_registry" ],
      [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", "struct_catch_1_1_i_generator_tracker" ],
      [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", "struct_catch_1_1_i_mutable_context" ],
      [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", "struct_catch_1_1_i_mutable_enum_values_registry" ],
      [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", "struct_catch_1_1_i_mutable_registry_hub" ],
      [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", "struct_catch_1_1_i_registry_hub" ],
      [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", "struct_catch_1_1_i_result_capture" ],
      [ "IRunner", "struct_catch_1_1_i_runner.html", "struct_catch_1_1_i_runner" ],
      [ "is_callable", "struct_catch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "struct_catch_1_1is__callable_3_01_fun_07_args_8_8_8_08_4.html", null ],
      [ "is_callable_tester", "struct_catch_1_1is__callable__tester.html", null ],
      [ "is_range", "struct_catch_1_1is__range.html", null ],
      [ "IStream", "struct_catch_1_1_i_stream.html", "struct_catch_1_1_i_stream" ],
      [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", "struct_catch_1_1_i_test_case_registry" ],
      [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", "struct_catch_1_1_i_test_invoker" ],
      [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", "struct_catch_1_1_i_transient_expression" ],
      [ "LazyExpression", "class_catch_1_1_lazy_expression.html", "class_catch_1_1_lazy_expression" ],
      [ "MatchExpr", "class_catch_1_1_match_expr.html", "class_catch_1_1_match_expr" ],
      [ "MessageBuilder", "struct_catch_1_1_message_builder.html", "struct_catch_1_1_message_builder" ],
      [ "MessageInfo", "struct_catch_1_1_message_info.html", "struct_catch_1_1_message_info" ],
      [ "MessageStream", "struct_catch_1_1_message_stream.html", "struct_catch_1_1_message_stream" ],
      [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", "struct_catch_1_1_name_and_tags" ],
      [ "NonCopyable", "class_catch_1_1_non_copyable.html", "class_catch_1_1_non_copyable" ],
      [ "Option", "class_catch_1_1_option.html", "class_catch_1_1_option" ],
      [ "pluralise", "struct_catch_1_1pluralise.html", "struct_catch_1_1pluralise" ],
      [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", "struct_catch_1_1_registrar_for_tag_aliases" ],
      [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", "struct_catch_1_1_result_disposition" ],
      [ "ResultWas", "struct_catch_1_1_result_was.html", "struct_catch_1_1_result_was" ],
      [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", "class_catch_1_1_reusable_string_stream" ],
      [ "RunTests", "struct_catch_1_1_run_tests.html", "struct_catch_1_1_run_tests" ],
      [ "ScopedMessage", "class_catch_1_1_scoped_message.html", "class_catch_1_1_scoped_message" ],
      [ "Section", "class_catch_1_1_section.html", "class_catch_1_1_section" ],
      [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", "struct_catch_1_1_section_end_info" ],
      [ "SectionInfo", "struct_catch_1_1_section_info.html", "struct_catch_1_1_section_info" ],
      [ "ShowDurations", "struct_catch_1_1_show_durations.html", "struct_catch_1_1_show_durations" ],
      [ "SimplePcg32", "class_catch_1_1_simple_pcg32.html", "class_catch_1_1_simple_pcg32" ],
      [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", "struct_catch_1_1_source_line_info" ],
      [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", "struct_catch_1_1_stream_end_stop" ],
      [ "StringMaker", "struct_catch_1_1_string_maker.html", null ],
      [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", null ],
      [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", null ],
      [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", null ],
      [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", null ],
      [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", null ],
      [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", null ],
      [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", null ],
      [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", null ],
      [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", null ],
      [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", null ],
      [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", null ],
      [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", null ],
      [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", null ],
      [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", null ],
      [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", null ],
      [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
      [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t_0f_s_z_0e_4.html", null ],
      [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", null ],
      [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", null ],
      [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", null ],
      [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", null ],
      [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", null ],
      [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", null ],
      [ "StringRef", "class_catch_1_1_string_ref.html", "class_catch_1_1_string_ref" ],
      [ "TestCase", "class_catch_1_1_test_case.html", "class_catch_1_1_test_case" ],
      [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", "struct_catch_1_1_test_case_info" ],
      [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
      [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", "class_catch_1_1_test_invoker_as_method" ],
      [ "Timer", "class_catch_1_1_timer.html", "class_catch_1_1_timer" ],
      [ "Totals", "struct_catch_1_1_totals.html", "struct_catch_1_1_totals" ],
      [ "true_given", "struct_catch_1_1true__given.html", null ],
      [ "UnaryExpr", "class_catch_1_1_unary_expr.html", "class_catch_1_1_unary_expr" ],
      [ "UseColour", "struct_catch_1_1_use_colour.html", "struct_catch_1_1_use_colour" ],
      [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", "struct_catch_1_1_wait_for_keypress" ],
      [ "WarnAbout", "struct_catch_1_1_warn_about.html", "struct_catch_1_1_warn_about" ]
    ] ],
    [ "Json", "namespace_json.html", [
      [ "BuiltStyledStreamWriter", "struct_json_1_1_built_styled_stream_writer.html", "struct_json_1_1_built_styled_stream_writer" ],
      [ "CharReader", "class_json_1_1_char_reader.html", "class_json_1_1_char_reader" ],
      [ "CharReaderBuilder", "class_json_1_1_char_reader_builder.html", "class_json_1_1_char_reader_builder" ],
      [ "CommentStyle", "struct_json_1_1_comment_style.html", "struct_json_1_1_comment_style" ],
      [ "Exception", "class_json_1_1_exception.html", "class_json_1_1_exception" ],
      [ "FastWriter", "class_json_1_1_fast_writer.html", "class_json_1_1_fast_writer" ],
      [ "Features", "class_json_1_1_features.html", "class_json_1_1_features" ],
      [ "LogicError", "class_json_1_1_logic_error.html", "class_json_1_1_logic_error" ],
      [ "OurCharReader", "class_json_1_1_our_char_reader.html", "class_json_1_1_our_char_reader" ],
      [ "OurFeatures", "class_json_1_1_our_features.html", "class_json_1_1_our_features" ],
      [ "OurReader", "class_json_1_1_our_reader.html", "class_json_1_1_our_reader" ],
      [ "Path", "class_json_1_1_path.html", "class_json_1_1_path" ],
      [ "PathArgument", "class_json_1_1_path_argument.html", "class_json_1_1_path_argument" ],
      [ "Reader", "class_json_1_1_reader.html", "class_json_1_1_reader" ],
      [ "RuntimeError", "class_json_1_1_runtime_error.html", "class_json_1_1_runtime_error" ],
      [ "SecureAllocator", "class_json_1_1_secure_allocator.html", "class_json_1_1_secure_allocator" ],
      [ "StaticString", "class_json_1_1_static_string.html", "class_json_1_1_static_string" ],
      [ "StreamWriter", "class_json_1_1_stream_writer.html", "class_json_1_1_stream_writer" ],
      [ "StreamWriterBuilder", "class_json_1_1_stream_writer_builder.html", "class_json_1_1_stream_writer_builder" ],
      [ "StyledStreamWriter", "class_json_1_1_styled_stream_writer.html", "class_json_1_1_styled_stream_writer" ],
      [ "StyledWriter", "class_json_1_1_styled_writer.html", "class_json_1_1_styled_writer" ],
      [ "Value", "class_json_1_1_value.html", "class_json_1_1_value" ],
      [ "ValueConstIterator", "class_json_1_1_value_const_iterator.html", "class_json_1_1_value_const_iterator" ],
      [ "ValueIterator", "class_json_1_1_value_iterator.html", "class_json_1_1_value_iterator" ],
      [ "ValueIteratorBase", "class_json_1_1_value_iterator_base.html", "class_json_1_1_value_iterator_base" ],
      [ "Writer", "class_json_1_1_writer.html", "class_json_1_1_writer" ]
    ] ],
    [ "log4cxx", "namespacelog4cxx.html", [
      [ "config", "namespacelog4cxx_1_1config.html", [
        [ "PropertySetter", "classlog4cxx_1_1config_1_1_property_setter.html", "classlog4cxx_1_1config_1_1_property_setter" ]
      ] ],
      [ "db", "namespacelog4cxx_1_1db.html", [
        [ "ODBCAppender", "classlog4cxx_1_1db_1_1_o_d_b_c_appender.html", "classlog4cxx_1_1db_1_1_o_d_b_c_appender" ],
        [ "SQLException", "classlog4cxx_1_1db_1_1_s_q_l_exception.html", "classlog4cxx_1_1db_1_1_s_q_l_exception" ]
      ] ],
      [ "filter", "namespacelog4cxx_1_1filter.html", [
        [ "AndFilter", "classlog4cxx_1_1filter_1_1_and_filter.html", "classlog4cxx_1_1filter_1_1_and_filter" ],
        [ "DenyAllFilter", "classlog4cxx_1_1filter_1_1_deny_all_filter.html", "classlog4cxx_1_1filter_1_1_deny_all_filter" ],
        [ "ExpressionFilter", "classlog4cxx_1_1filter_1_1_expression_filter.html", "classlog4cxx_1_1filter_1_1_expression_filter" ],
        [ "LevelMatchFilter", "classlog4cxx_1_1filter_1_1_level_match_filter.html", "classlog4cxx_1_1filter_1_1_level_match_filter" ],
        [ "LevelRangeFilter", "classlog4cxx_1_1filter_1_1_level_range_filter.html", "classlog4cxx_1_1filter_1_1_level_range_filter" ],
        [ "LocationInfoFilter", "classlog4cxx_1_1filter_1_1_location_info_filter.html", "classlog4cxx_1_1filter_1_1_location_info_filter" ],
        [ "LoggerMatchFilter", "classlog4cxx_1_1filter_1_1_logger_match_filter.html", "classlog4cxx_1_1filter_1_1_logger_match_filter" ],
        [ "MapFilter", "classlog4cxx_1_1filter_1_1_map_filter.html", "classlog4cxx_1_1filter_1_1_map_filter" ],
        [ "PropertyFilter", "classlog4cxx_1_1filter_1_1_property_filter.html", "classlog4cxx_1_1filter_1_1_property_filter" ],
        [ "StringMatchFilter", "classlog4cxx_1_1filter_1_1_string_match_filter.html", "classlog4cxx_1_1filter_1_1_string_match_filter" ]
      ] ],
      [ "helpers", "namespacelog4cxx_1_1helpers.html", [
        [ "AbsoluteTimeDateFormat", "classlog4cxx_1_1helpers_1_1_absolute_time_date_format.html", "classlog4cxx_1_1helpers_1_1_absolute_time_date_format" ],
        [ "AppenderAttachableImpl", "classlog4cxx_1_1helpers_1_1_appender_attachable_impl.html", "classlog4cxx_1_1helpers_1_1_appender_attachable_impl" ],
        [ "APRInitializer", "classlog4cxx_1_1helpers_1_1_a_p_r_initializer.html", "classlog4cxx_1_1helpers_1_1_a_p_r_initializer" ],
        [ "BindException", "classlog4cxx_1_1helpers_1_1_bind_exception.html", "classlog4cxx_1_1helpers_1_1_bind_exception" ],
        [ "BufferedOutputStream", "classlog4cxx_1_1helpers_1_1_buffered_output_stream.html", "classlog4cxx_1_1helpers_1_1_buffered_output_stream" ],
        [ "BufferedWriter", "classlog4cxx_1_1helpers_1_1_buffered_writer.html", "classlog4cxx_1_1helpers_1_1_buffered_writer" ],
        [ "ByteArrayInputStream", "classlog4cxx_1_1helpers_1_1_byte_array_input_stream.html", "classlog4cxx_1_1helpers_1_1_byte_array_input_stream" ],
        [ "ByteArrayOutputStream", "classlog4cxx_1_1helpers_1_1_byte_array_output_stream.html", "classlog4cxx_1_1helpers_1_1_byte_array_output_stream" ],
        [ "ByteBuffer", "classlog4cxx_1_1helpers_1_1_byte_buffer.html", "classlog4cxx_1_1helpers_1_1_byte_buffer" ],
        [ "CharMessageBuffer", "classlog4cxx_1_1helpers_1_1_char_message_buffer.html", "classlog4cxx_1_1helpers_1_1_char_message_buffer" ],
        [ "CharsetDecoder", "classlog4cxx_1_1helpers_1_1_charset_decoder.html", "classlog4cxx_1_1helpers_1_1_charset_decoder" ],
        [ "CharsetEncoder", "classlog4cxx_1_1helpers_1_1_charset_encoder.html", "classlog4cxx_1_1helpers_1_1_charset_encoder" ],
        [ "Class", "classlog4cxx_1_1helpers_1_1_class.html", "classlog4cxx_1_1helpers_1_1_class" ],
        [ "ClassNotFoundException", "classlog4cxx_1_1helpers_1_1_class_not_found_exception.html", "classlog4cxx_1_1helpers_1_1_class_not_found_exception" ],
        [ "ClassRegistration", "classlog4cxx_1_1helpers_1_1_class_registration.html", "classlog4cxx_1_1helpers_1_1_class_registration" ],
        [ "ClosedChannelException", "classlog4cxx_1_1helpers_1_1_closed_channel_exception.html", "classlog4cxx_1_1helpers_1_1_closed_channel_exception" ],
        [ "ConnectException", "classlog4cxx_1_1helpers_1_1_connect_exception.html", "classlog4cxx_1_1helpers_1_1_connect_exception" ],
        [ "CyclicBuffer", "classlog4cxx_1_1helpers_1_1_cyclic_buffer.html", "classlog4cxx_1_1helpers_1_1_cyclic_buffer" ],
        [ "DatagramPacket", "classlog4cxx_1_1helpers_1_1_datagram_packet.html", "classlog4cxx_1_1helpers_1_1_datagram_packet" ],
        [ "DatagramSocket", "classlog4cxx_1_1helpers_1_1_datagram_socket.html", "classlog4cxx_1_1helpers_1_1_datagram_socket" ],
        [ "Date", "classlog4cxx_1_1helpers_1_1_date.html", "classlog4cxx_1_1helpers_1_1_date" ],
        [ "DateFormat", "classlog4cxx_1_1helpers_1_1_date_format.html", "classlog4cxx_1_1helpers_1_1_date_format" ],
        [ "DateLayout", "classlog4cxx_1_1helpers_1_1_date_layout.html", "classlog4cxx_1_1helpers_1_1_date_layout" ],
        [ "DateTimeDateFormat", "classlog4cxx_1_1helpers_1_1_date_time_date_format.html", "classlog4cxx_1_1helpers_1_1_date_time_date_format" ],
        [ "DOMException", "classlog4cxx_1_1helpers_1_1_d_o_m_exception.html", "classlog4cxx_1_1helpers_1_1_d_o_m_exception" ],
        [ "Exception", "classlog4cxx_1_1helpers_1_1_exception.html", "classlog4cxx_1_1helpers_1_1_exception" ],
        [ "FileInputStream", "classlog4cxx_1_1helpers_1_1_file_input_stream.html", "classlog4cxx_1_1helpers_1_1_file_input_stream" ],
        [ "FileOutputStream", "classlog4cxx_1_1helpers_1_1_file_output_stream.html", "classlog4cxx_1_1helpers_1_1_file_output_stream" ],
        [ "FileWatchdog", "classlog4cxx_1_1helpers_1_1_file_watchdog.html", "classlog4cxx_1_1helpers_1_1_file_watchdog" ],
        [ "IllegalArgumentException", "classlog4cxx_1_1helpers_1_1_illegal_argument_exception.html", "classlog4cxx_1_1helpers_1_1_illegal_argument_exception" ],
        [ "IllegalMonitorStateException", "classlog4cxx_1_1helpers_1_1_illegal_monitor_state_exception.html", "classlog4cxx_1_1helpers_1_1_illegal_monitor_state_exception" ],
        [ "IllegalStateException", "classlog4cxx_1_1helpers_1_1_illegal_state_exception.html", "classlog4cxx_1_1helpers_1_1_illegal_state_exception" ],
        [ "InetAddress", "classlog4cxx_1_1helpers_1_1_inet_address.html", "classlog4cxx_1_1helpers_1_1_inet_address" ],
        [ "InputStream", "classlog4cxx_1_1helpers_1_1_input_stream.html", "classlog4cxx_1_1helpers_1_1_input_stream" ],
        [ "InputStreamReader", "classlog4cxx_1_1helpers_1_1_input_stream_reader.html", "classlog4cxx_1_1helpers_1_1_input_stream_reader" ],
        [ "InstantiationException", "classlog4cxx_1_1helpers_1_1_instantiation_exception.html", "classlog4cxx_1_1helpers_1_1_instantiation_exception" ],
        [ "Integer", "classlog4cxx_1_1helpers_1_1_integer.html", "classlog4cxx_1_1helpers_1_1_integer" ],
        [ "InterruptedException", "classlog4cxx_1_1helpers_1_1_interrupted_exception.html", "classlog4cxx_1_1helpers_1_1_interrupted_exception" ],
        [ "InterruptedIOException", "classlog4cxx_1_1helpers_1_1_interrupted_i_o_exception.html", "classlog4cxx_1_1helpers_1_1_interrupted_i_o_exception" ],
        [ "IOException", "classlog4cxx_1_1helpers_1_1_i_o_exception.html", "classlog4cxx_1_1helpers_1_1_i_o_exception" ],
        [ "ISO8601DateFormat", "classlog4cxx_1_1helpers_1_1_i_s_o8601_date_format.html", "classlog4cxx_1_1helpers_1_1_i_s_o8601_date_format" ],
        [ "Loader", "classlog4cxx_1_1helpers_1_1_loader.html", null ],
        [ "Locale", "classlog4cxx_1_1helpers_1_1_locale.html", "classlog4cxx_1_1helpers_1_1_locale" ],
        [ "LogLog", "classlog4cxx_1_1helpers_1_1_log_log.html", null ],
        [ "MissingResourceException", "classlog4cxx_1_1helpers_1_1_missing_resource_exception.html", "classlog4cxx_1_1helpers_1_1_missing_resource_exception" ],
        [ "NoSuchElementException", "classlog4cxx_1_1helpers_1_1_no_such_element_exception.html", "classlog4cxx_1_1helpers_1_1_no_such_element_exception" ],
        [ "NullPointerException", "classlog4cxx_1_1helpers_1_1_null_pointer_exception.html", "classlog4cxx_1_1helpers_1_1_null_pointer_exception" ],
        [ "Object", "classlog4cxx_1_1helpers_1_1_object.html", "classlog4cxx_1_1helpers_1_1_object" ],
        [ "ObjectOutputStream", "classlog4cxx_1_1helpers_1_1_object_output_stream.html", "classlog4cxx_1_1helpers_1_1_object_output_stream" ],
        [ "OnlyOnceErrorHandler", "classlog4cxx_1_1helpers_1_1_only_once_error_handler.html", "classlog4cxx_1_1helpers_1_1_only_once_error_handler" ],
        [ "OptionConverter", "classlog4cxx_1_1helpers_1_1_option_converter.html", null ],
        [ "OutputStream", "classlog4cxx_1_1helpers_1_1_output_stream.html", "classlog4cxx_1_1helpers_1_1_output_stream" ],
        [ "OutputStreamWriter", "classlog4cxx_1_1helpers_1_1_output_stream_writer.html", "classlog4cxx_1_1helpers_1_1_output_stream_writer" ],
        [ "Pool", "classlog4cxx_1_1helpers_1_1_pool.html", "classlog4cxx_1_1helpers_1_1_pool" ],
        [ "PoolException", "classlog4cxx_1_1helpers_1_1_pool_exception.html", "classlog4cxx_1_1helpers_1_1_pool_exception" ],
        [ "Properties", "classlog4cxx_1_1helpers_1_1_properties.html", "classlog4cxx_1_1helpers_1_1_properties" ],
        [ "PropertyResourceBundle", "classlog4cxx_1_1helpers_1_1_property_resource_bundle.html", "classlog4cxx_1_1helpers_1_1_property_resource_bundle" ],
        [ "Reader", "classlog4cxx_1_1helpers_1_1_reader.html", "classlog4cxx_1_1helpers_1_1_reader" ],
        [ "RelativeTimeDateFormat", "classlog4cxx_1_1helpers_1_1_relative_time_date_format.html", "classlog4cxx_1_1helpers_1_1_relative_time_date_format" ],
        [ "ResourceBundle", "classlog4cxx_1_1helpers_1_1_resource_bundle.html", "classlog4cxx_1_1helpers_1_1_resource_bundle" ],
        [ "RuntimeException", "classlog4cxx_1_1helpers_1_1_runtime_exception.html", "classlog4cxx_1_1helpers_1_1_runtime_exception" ],
        [ "ServerSocket", "classlog4cxx_1_1helpers_1_1_server_socket.html", "classlog4cxx_1_1helpers_1_1_server_socket" ],
        [ "SimpleDateFormat", "classlog4cxx_1_1helpers_1_1_simple_date_format.html", "classlog4cxx_1_1helpers_1_1_simple_date_format" ],
        [ "Socket", "classlog4cxx_1_1helpers_1_1_socket.html", "classlog4cxx_1_1helpers_1_1_socket" ],
        [ "SocketException", "classlog4cxx_1_1helpers_1_1_socket_exception.html", "classlog4cxx_1_1helpers_1_1_socket_exception" ],
        [ "SocketOutputStream", "classlog4cxx_1_1helpers_1_1_socket_output_stream.html", "classlog4cxx_1_1helpers_1_1_socket_output_stream" ],
        [ "SocketTimeoutException", "classlog4cxx_1_1helpers_1_1_socket_timeout_exception.html", "classlog4cxx_1_1helpers_1_1_socket_timeout_exception" ],
        [ "StrftimeDateFormat", "classlog4cxx_1_1helpers_1_1_strftime_date_format.html", "classlog4cxx_1_1helpers_1_1_strftime_date_format" ],
        [ "StrictMath", "classlog4cxx_1_1helpers_1_1_strict_math.html", null ],
        [ "StringHelper", "classlog4cxx_1_1helpers_1_1_string_helper.html", null ],
        [ "StringTokenizer", "classlog4cxx_1_1helpers_1_1_string_tokenizer.html", "classlog4cxx_1_1helpers_1_1_string_tokenizer" ],
        [ "SyslogWriter", "classlog4cxx_1_1helpers_1_1_syslog_writer.html", "classlog4cxx_1_1helpers_1_1_syslog_writer" ],
        [ "System", "classlog4cxx_1_1helpers_1_1_system.html", null ],
        [ "SystemErrWriter", "classlog4cxx_1_1helpers_1_1_system_err_writer.html", "classlog4cxx_1_1helpers_1_1_system_err_writer" ],
        [ "SystemOutWriter", "classlog4cxx_1_1helpers_1_1_system_out_writer.html", "classlog4cxx_1_1helpers_1_1_system_out_writer" ],
        [ "ThreadException", "classlog4cxx_1_1helpers_1_1_thread_exception.html", "classlog4cxx_1_1helpers_1_1_thread_exception" ],
        [ "ThreadLocal", "classlog4cxx_1_1helpers_1_1_thread_local.html", "classlog4cxx_1_1helpers_1_1_thread_local" ],
        [ "ThreadSpecificData", "classlog4cxx_1_1helpers_1_1_thread_specific_data.html", "classlog4cxx_1_1helpers_1_1_thread_specific_data" ],
        [ "ThreadUtility", "classlog4cxx_1_1helpers_1_1_thread_utility.html", "classlog4cxx_1_1helpers_1_1_thread_utility" ],
        [ "TimeZone", "classlog4cxx_1_1helpers_1_1_time_zone.html", "classlog4cxx_1_1helpers_1_1_time_zone" ],
        [ "Transcoder", "classlog4cxx_1_1helpers_1_1_transcoder.html", null ],
        [ "TranscoderException", "classlog4cxx_1_1helpers_1_1_transcoder_exception.html", "classlog4cxx_1_1helpers_1_1_transcoder_exception" ],
        [ "Transform", "classlog4cxx_1_1helpers_1_1_transform.html", null ],
        [ "UnknownHostException", "classlog4cxx_1_1helpers_1_1_unknown_host_exception.html", "classlog4cxx_1_1helpers_1_1_unknown_host_exception" ],
        [ "Writer", "classlog4cxx_1_1helpers_1_1_writer.html", "classlog4cxx_1_1helpers_1_1_writer" ],
        [ "XMLDOMDocument", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_document.html", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_document" ],
        [ "XMLDOMElement", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_element.html", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_element" ],
        [ "XMLDOMNode", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_node.html", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_node" ],
        [ "XMLDOMNodeList", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_node_list.html", "classlog4cxx_1_1helpers_1_1_x_m_l_d_o_m_node_list" ]
      ] ],
      [ "net", "namespacelog4cxx_1_1net.html", [
        [ "SMTPAppender", "classlog4cxx_1_1net_1_1_s_m_t_p_appender.html", "classlog4cxx_1_1net_1_1_s_m_t_p_appender" ],
        [ "SocketAppender", "classlog4cxx_1_1net_1_1_socket_appender.html", "classlog4cxx_1_1net_1_1_socket_appender" ],
        [ "SocketAppenderSkeleton", "classlog4cxx_1_1net_1_1_socket_appender_skeleton.html", "classlog4cxx_1_1net_1_1_socket_appender_skeleton" ],
        [ "SocketHubAppender", "classlog4cxx_1_1net_1_1_socket_hub_appender.html", "classlog4cxx_1_1net_1_1_socket_hub_appender" ],
        [ "SyslogAppender", "classlog4cxx_1_1net_1_1_syslog_appender.html", "classlog4cxx_1_1net_1_1_syslog_appender" ],
        [ "TelnetAppender", "classlog4cxx_1_1net_1_1_telnet_appender.html", "classlog4cxx_1_1net_1_1_telnet_appender" ],
        [ "XMLSocketAppender", "classlog4cxx_1_1net_1_1_x_m_l_socket_appender.html", "classlog4cxx_1_1net_1_1_x_m_l_socket_appender" ]
      ] ],
      [ "nt", "namespacelog4cxx_1_1nt.html", [
        [ "NTEventLogAppender", "classlog4cxx_1_1nt_1_1_n_t_event_log_appender.html", "classlog4cxx_1_1nt_1_1_n_t_event_log_appender" ],
        [ "OutputDebugStringAppender", "classlog4cxx_1_1nt_1_1_output_debug_string_appender.html", "classlog4cxx_1_1nt_1_1_output_debug_string_appender" ]
      ] ],
      [ "pattern", "namespacelog4cxx_1_1pattern.html", [
        [ "CachedDateFormat", "classlog4cxx_1_1pattern_1_1_cached_date_format.html", "classlog4cxx_1_1pattern_1_1_cached_date_format" ],
        [ "ClassNamePatternConverter", "classlog4cxx_1_1pattern_1_1_class_name_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_class_name_pattern_converter" ],
        [ "ColorEndPatternConverter", "classlog4cxx_1_1pattern_1_1_color_end_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_color_end_pattern_converter" ],
        [ "ColorStartPatternConverter", "classlog4cxx_1_1pattern_1_1_color_start_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_color_start_pattern_converter" ],
        [ "DatePatternConverter", "classlog4cxx_1_1pattern_1_1_date_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_date_pattern_converter" ],
        [ "FileDatePatternConverter", "classlog4cxx_1_1pattern_1_1_file_date_pattern_converter.html", null ],
        [ "FileLocationPatternConverter", "classlog4cxx_1_1pattern_1_1_file_location_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_file_location_pattern_converter" ],
        [ "FormattingInfo", "classlog4cxx_1_1pattern_1_1_formatting_info.html", "classlog4cxx_1_1pattern_1_1_formatting_info" ],
        [ "FullLocationPatternConverter", "classlog4cxx_1_1pattern_1_1_full_location_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_full_location_pattern_converter" ],
        [ "IntegerPatternConverter", "classlog4cxx_1_1pattern_1_1_integer_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_integer_pattern_converter" ],
        [ "LevelPatternConverter", "classlog4cxx_1_1pattern_1_1_level_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_level_pattern_converter" ],
        [ "LineLocationPatternConverter", "classlog4cxx_1_1pattern_1_1_line_location_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_line_location_pattern_converter" ],
        [ "LineSeparatorPatternConverter", "classlog4cxx_1_1pattern_1_1_line_separator_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_line_separator_pattern_converter" ],
        [ "LiteralPatternConverter", "classlog4cxx_1_1pattern_1_1_literal_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_literal_pattern_converter" ],
        [ "LoggerPatternConverter", "classlog4cxx_1_1pattern_1_1_logger_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_logger_pattern_converter" ],
        [ "LoggingEventPatternConverter", "classlog4cxx_1_1pattern_1_1_logging_event_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_logging_event_pattern_converter" ],
        [ "MessagePatternConverter", "classlog4cxx_1_1pattern_1_1_message_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_message_pattern_converter" ],
        [ "MethodLocationPatternConverter", "classlog4cxx_1_1pattern_1_1_method_location_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_method_location_pattern_converter" ],
        [ "NameAbbreviator", "classlog4cxx_1_1pattern_1_1_name_abbreviator.html", "classlog4cxx_1_1pattern_1_1_name_abbreviator" ],
        [ "NamePatternConverter", "classlog4cxx_1_1pattern_1_1_name_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_name_pattern_converter" ],
        [ "NDCPatternConverter", "classlog4cxx_1_1pattern_1_1_n_d_c_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_n_d_c_pattern_converter" ],
        [ "PatternConverter", "classlog4cxx_1_1pattern_1_1_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_pattern_converter" ],
        [ "PatternParser", "classlog4cxx_1_1pattern_1_1_pattern_parser.html", null ],
        [ "PropertiesPatternConverter", "classlog4cxx_1_1pattern_1_1_properties_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_properties_pattern_converter" ],
        [ "RelativeTimePatternConverter", "classlog4cxx_1_1pattern_1_1_relative_time_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_relative_time_pattern_converter" ],
        [ "ShortFileLocationPatternConverter", "classlog4cxx_1_1pattern_1_1_short_file_location_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_short_file_location_pattern_converter" ],
        [ "ThreadPatternConverter", "classlog4cxx_1_1pattern_1_1_thread_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_thread_pattern_converter" ],
        [ "ThreadUsernamePatternConverter", "classlog4cxx_1_1pattern_1_1_thread_username_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_thread_username_pattern_converter" ],
        [ "ThrowableInformationPatternConverter", "classlog4cxx_1_1pattern_1_1_throwable_information_pattern_converter.html", "classlog4cxx_1_1pattern_1_1_throwable_information_pattern_converter" ]
      ] ],
      [ "rolling", "namespacelog4cxx_1_1rolling.html", [
        [ "Action", "classlog4cxx_1_1rolling_1_1_action.html", "classlog4cxx_1_1rolling_1_1_action" ],
        [ "FileRenameAction", "classlog4cxx_1_1rolling_1_1_file_rename_action.html", "classlog4cxx_1_1rolling_1_1_file_rename_action" ],
        [ "FilterBasedTriggeringPolicy", "classlog4cxx_1_1rolling_1_1_filter_based_triggering_policy.html", "classlog4cxx_1_1rolling_1_1_filter_based_triggering_policy" ],
        [ "FixedWindowRollingPolicy", "classlog4cxx_1_1rolling_1_1_fixed_window_rolling_policy.html", "classlog4cxx_1_1rolling_1_1_fixed_window_rolling_policy" ],
        [ "GZCompressAction", "classlog4cxx_1_1rolling_1_1_g_z_compress_action.html", "classlog4cxx_1_1rolling_1_1_g_z_compress_action" ],
        [ "ManualTriggeringPolicy", "classlog4cxx_1_1rolling_1_1_manual_triggering_policy.html", "classlog4cxx_1_1rolling_1_1_manual_triggering_policy" ],
        [ "RollingFileAppender", "classlog4cxx_1_1rolling_1_1_rolling_file_appender.html", "classlog4cxx_1_1rolling_1_1_rolling_file_appender" ],
        [ "RollingFileAppenderSkeleton", "classlog4cxx_1_1rolling_1_1_rolling_file_appender_skeleton.html", "classlog4cxx_1_1rolling_1_1_rolling_file_appender_skeleton" ],
        [ "RollingPolicy", "classlog4cxx_1_1rolling_1_1_rolling_policy.html", "classlog4cxx_1_1rolling_1_1_rolling_policy" ],
        [ "RollingPolicyBase", "classlog4cxx_1_1rolling_1_1_rolling_policy_base.html", "classlog4cxx_1_1rolling_1_1_rolling_policy_base" ],
        [ "RolloverDescription", "classlog4cxx_1_1rolling_1_1_rollover_description.html", "classlog4cxx_1_1rolling_1_1_rollover_description" ],
        [ "SizeBasedTriggeringPolicy", "classlog4cxx_1_1rolling_1_1_size_based_triggering_policy.html", "classlog4cxx_1_1rolling_1_1_size_based_triggering_policy" ],
        [ "TimeBasedRollingPolicy", "classlog4cxx_1_1rolling_1_1_time_based_rolling_policy.html", "classlog4cxx_1_1rolling_1_1_time_based_rolling_policy" ],
        [ "TriggeringPolicy", "classlog4cxx_1_1rolling_1_1_triggering_policy.html", "classlog4cxx_1_1rolling_1_1_triggering_policy" ],
        [ "ZipCompressAction", "classlog4cxx_1_1rolling_1_1_zip_compress_action.html", "classlog4cxx_1_1rolling_1_1_zip_compress_action" ]
      ] ],
      [ "spi", "namespacelog4cxx_1_1spi.html", [
        [ "AppenderAttachable", "classlog4cxx_1_1spi_1_1_appender_attachable.html", "classlog4cxx_1_1spi_1_1_appender_attachable" ],
        [ "Configurator", "classlog4cxx_1_1spi_1_1_configurator.html", "classlog4cxx_1_1spi_1_1_configurator" ],
        [ "DefaultRepositorySelector", "classlog4cxx_1_1spi_1_1_default_repository_selector.html", "classlog4cxx_1_1spi_1_1_default_repository_selector" ],
        [ "ErrorCode", "classlog4cxx_1_1spi_1_1_error_code.html", null ],
        [ "ErrorHandler", "classlog4cxx_1_1spi_1_1_error_handler.html", "classlog4cxx_1_1spi_1_1_error_handler" ],
        [ "Filter", "classlog4cxx_1_1spi_1_1_filter.html", "classlog4cxx_1_1spi_1_1_filter" ],
        [ "HierarchyEventListener", "classlog4cxx_1_1spi_1_1_hierarchy_event_listener.html", "classlog4cxx_1_1spi_1_1_hierarchy_event_listener" ],
        [ "LocationInfo", "classlog4cxx_1_1spi_1_1_location_info.html", "classlog4cxx_1_1spi_1_1_location_info" ],
        [ "LoggerFactory", "classlog4cxx_1_1spi_1_1_logger_factory.html", "classlog4cxx_1_1spi_1_1_logger_factory" ],
        [ "LoggerRepository", "classlog4cxx_1_1spi_1_1_logger_repository.html", "classlog4cxx_1_1spi_1_1_logger_repository" ],
        [ "LoggingEvent", "classlog4cxx_1_1spi_1_1_logging_event.html", "classlog4cxx_1_1spi_1_1_logging_event" ],
        [ "OptionHandler", "classlog4cxx_1_1spi_1_1_option_handler.html", "classlog4cxx_1_1spi_1_1_option_handler" ],
        [ "RepositorySelector", "classlog4cxx_1_1spi_1_1_repository_selector.html", "classlog4cxx_1_1spi_1_1_repository_selector" ],
        [ "RootLogger", "classlog4cxx_1_1spi_1_1_root_logger.html", "classlog4cxx_1_1spi_1_1_root_logger" ],
        [ "TriggeringEventEvaluator", "classlog4cxx_1_1spi_1_1_triggering_event_evaluator.html", "classlog4cxx_1_1spi_1_1_triggering_event_evaluator" ]
      ] ],
      [ "varia", "namespacelog4cxx_1_1varia.html", [
        [ "FallbackErrorHandler", "classlog4cxx_1_1varia_1_1_fallback_error_handler.html", "classlog4cxx_1_1varia_1_1_fallback_error_handler" ]
      ] ],
      [ "xml", "namespacelog4cxx_1_1xml.html", [
        [ "DOMConfigurator", "classlog4cxx_1_1xml_1_1_d_o_m_configurator.html", "classlog4cxx_1_1xml_1_1_d_o_m_configurator" ],
        [ "XMLLayout", "classlog4cxx_1_1xml_1_1_x_m_l_layout.html", "classlog4cxx_1_1xml_1_1_x_m_l_layout" ]
      ] ],
      [ "Appender", "classlog4cxx_1_1_appender.html", "classlog4cxx_1_1_appender" ],
      [ "AppenderSkeleton", "classlog4cxx_1_1_appender_skeleton.html", "classlog4cxx_1_1_appender_skeleton" ],
      [ "AsyncAppender", "classlog4cxx_1_1_async_appender.html", "classlog4cxx_1_1_async_appender" ],
      [ "BasicConfigurator", "classlog4cxx_1_1_basic_configurator.html", "classlog4cxx_1_1_basic_configurator" ],
      [ "ConsoleAppender", "classlog4cxx_1_1_console_appender.html", "classlog4cxx_1_1_console_appender" ],
      [ "DailyRollingFileAppender", "classlog4cxx_1_1_daily_rolling_file_appender.html", "classlog4cxx_1_1_daily_rolling_file_appender" ],
      [ "DefaultConfigurator", "classlog4cxx_1_1_default_configurator.html", null ],
      [ "DefaultLoggerFactory", "classlog4cxx_1_1_default_logger_factory.html", "classlog4cxx_1_1_default_logger_factory" ],
      [ "File", "classlog4cxx_1_1_file.html", "classlog4cxx_1_1_file" ],
      [ "FileAppender", "classlog4cxx_1_1_file_appender.html", "classlog4cxx_1_1_file_appender" ],
      [ "Hierarchy", "classlog4cxx_1_1_hierarchy.html", "classlog4cxx_1_1_hierarchy" ],
      [ "HTMLLayout", "classlog4cxx_1_1_h_t_m_l_layout.html", "classlog4cxx_1_1_h_t_m_l_layout" ],
      [ "JSONLayout", "classlog4cxx_1_1_j_s_o_n_layout.html", "classlog4cxx_1_1_j_s_o_n_layout" ],
      [ "Layout", "classlog4cxx_1_1_layout.html", "classlog4cxx_1_1_layout" ],
      [ "Level", "classlog4cxx_1_1_level.html", "classlog4cxx_1_1_level" ],
      [ "Logger", "classlog4cxx_1_1_logger.html", "classlog4cxx_1_1_logger" ],
      [ "LogManager", "classlog4cxx_1_1_log_manager.html", null ],
      [ "logstream", "classlog4cxx_1_1logstream.html", "classlog4cxx_1_1logstream" ],
      [ "logstream_base", "classlog4cxx_1_1logstream__base.html", "classlog4cxx_1_1logstream__base" ],
      [ "MDC", "classlog4cxx_1_1_m_d_c.html", "classlog4cxx_1_1_m_d_c" ],
      [ "NDC", "classlog4cxx_1_1_n_d_c.html", "classlog4cxx_1_1_n_d_c" ],
      [ "PatternLayout", "classlog4cxx_1_1_pattern_layout.html", "classlog4cxx_1_1_pattern_layout" ],
      [ "PropertyConfigurator", "classlog4cxx_1_1_property_configurator.html", "classlog4cxx_1_1_property_configurator" ],
      [ "RollingFileAppender", "classlog4cxx_1_1_rolling_file_appender.html", "classlog4cxx_1_1_rolling_file_appender" ],
      [ "SimpleLayout", "classlog4cxx_1_1_simple_layout.html", "classlog4cxx_1_1_simple_layout" ],
      [ "TTCCLayout", "classlog4cxx_1_1_t_t_c_c_layout.html", "classlog4cxx_1_1_t_t_c_c_layout" ],
      [ "WriterAppender", "classlog4cxx_1_1_writer_appender.html", "classlog4cxx_1_1_writer_appender" ]
    ] ],
    [ "Add", "class_add.html", "class_add" ],
    [ "AddNode", "class_add_node.html", "class_add_node" ],
    [ "BinaryOperatorNode", "class_binary_operator_node.html", "class_binary_operator_node" ],
    [ "BST", "class_b_s_t.html", "class_b_s_t" ],
    [ "Building", "class_building.html", "class_building" ],
    [ "Card", "struct_card.html", "struct_card" ],
    [ "Catch_global_namespace_dummy", "struct_catch__global__namespace__dummy.html", null ],
    [ "Constant", "class_constant.html", "class_constant" ],
    [ "Deck", "class_deck.html", "class_deck" ],
    [ "Div", "class_div.html", "class_div" ],
    [ "DivideNode", "class_divide_node.html", "class_divide_node" ],
    [ "Elevator", "class_elevator.html", "class_elevator" ],
    [ "ExpressionNode", "class_expression_node.html", "class_expression_node" ],
    [ "ExpressionTree", "class_expression_tree.html", "class_expression_tree" ],
    [ "Floor", "class_floor.html", "class_floor" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameDriver", "class_game_driver.html", "class_game_driver" ],
    [ "Hand", "class_hand.html", "class_hand" ],
    [ "InputOutput", "class_input_output.html", "class_input_output" ],
    [ "JsonPokerTests", "class_json_poker_tests.html", "class_json_poker_tests" ],
    [ "JsonProbabilityTests", "class_json_probability_tests.html", "class_json_probability_tests" ],
    [ "Mul", "class_mul.html", "class_mul" ],
    [ "MultiplyNode", "class_multiply_node.html", "class_multiply_node" ],
    [ "Node", "class_node.html", "class_node" ],
    [ "Passenger", "class_passenger.html", "class_passenger" ],
    [ "PokerGame", "class_poker_game.html", "class_poker_game" ],
    [ "Probability", "class_probability.html", "class_probability" ],
    [ "RunSimulation", "class_run_simulation.html", "class_run_simulation" ],
    [ "Statistic", "class_statistic.html", "class_statistic" ],
    [ "Sub", "class_sub.html", "class_sub" ],
    [ "SubtractNode", "class_subtract_node.html", "class_subtract_node" ],
    [ "TreeNode", "class_tree_node.html", "class_tree_node" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "ValueNode", "class_value_node.html", "class_value_node" ],
    [ "Variable", "class_variable.html", "class_variable" ]
];