var files_dup =
[
    [ "json", "dir_324bfb8aa525ab5f73bcc4531b7e0708.html", "dir_324bfb8aa525ab5f73bcc4531b7e0708" ],
    [ "log4cxx", "dir_cb3fb93c4b0338d3af31735a9ec7b139.html", "dir_cb3fb93c4b0338d3af31735a9ec7b139" ],
    [ "Probability", "dir_578c22554e813618730a5dae1cebe37e.html", "dir_578c22554e813618730a5dae1cebe37e" ],
    [ "catch.hpp", "catch_8hpp.html", "catch_8hpp" ],
    [ "elevator.cpp", "elevator_8cpp.html", "elevator_8cpp" ],
    [ "ExpressionEvaluator.cpp", "_expression_evaluator_8cpp.html", "_expression_evaluator_8cpp" ],
    [ "FiveCardDraw.cpp", "_five_card_draw_8cpp.html", "_five_card_draw_8cpp" ],
    [ "InputOutput.cpp", "_input_output_8cpp.html", "_input_output_8cpp" ],
    [ "jsoncpp.cpp", "jsoncpp_8cpp.html", "jsoncpp_8cpp" ],
    [ "PokerHandRanking.cpp", "_poker_hand_ranking_8cpp.html", "_poker_hand_ranking_8cpp" ],
    [ "PokerHandsV2.cpp", "_poker_hands_v2_8cpp.html", "_poker_hands_v2_8cpp" ],
    [ "Probability.cpp", "_probability_8cpp.html", "_probability_8cpp" ],
    [ "Statistic.cpp", "_statistic_8cpp.html", "_statistic_8cpp" ],
    [ "StatisticMain.cpp", "_statistic_main_8cpp.html", "_statistic_main_8cpp" ],
    [ "test.cpp", "test_8cpp.html", "test_8cpp" ],
    [ "test2.cpp", "test2_8cpp.html", "test2_8cpp" ],
    [ "test3.cpp", "test3_8cpp.html", "test3_8cpp" ],
    [ "test4.cpp", "test4_8cpp.html", "test4_8cpp" ],
    [ "TicTacToe.cpp", "_tic_tac_toe_8cpp.html", "_tic_tac_toe_8cpp" ],
    [ "Triangle.cpp", "_triangle_8cpp.html", "_triangle_8cpp" ],
    [ "TriangleMain.cpp", "_triangle_main_8cpp.html", "_triangle_main_8cpp" ],
    [ "UnitTest_Statistic.cpp", "_unit_test___statistic_8cpp.html", "_unit_test___statistic_8cpp" ],
    [ "UnitTest_Triangle.cpp", "_unit_test___triangle_8cpp.html", "_unit_test___triangle_8cpp" ]
];